[package]
name = "toy-external-events"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" }
wasmtime-wasi-io = { git = "https://github.com/bytecodealliance/wasmtime" }
futures = "*"
bytes = "*"
