[package]
name = "toy-external-events"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
wasmtime = { path = "../wasmtime/crates/wasmtime", default-features = false }
wasmtime-wasi-io = { path = "../wasmtime/crates/wasi-io", default-features = false }
